apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    type: fluentd
  logStore:
    lokistack:
      name: lokistack-sample
    type: lokistack
  managementState: Unmanaged
